name = "ZFCAczel"
defaultTargets = ["ZFCAczel"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.31.0"

# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "main"

[[lean_lib]]
name = "ZFCAczel"

[[lean_exe]]
name = "zfca"
root = "ZFCAczelMain"
